name: Performance Tests
on:
  push:
    branches:
      - develop
      - feature/*
      - hotfix/*

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Performance Tests
        run: cd reassure && ./reassure-tests.sh
      - name: Run Danger.js
        run: npm danger ci
