name: PR-Checks
on:
  push:
    branches:
      - develop
      - feature/*
      - hotfix/*
      
jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - with:
          node-version: 18.x
          cache: npm
      - name: Lint Checks
        run: npm lint
      - name: Type checks
        run: npm typecheck
      
